<!DOCTYPE html>
<html lang="en" data-textdirection="ltr">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">

	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">

	<style type="text/css">
		* {
			font-family: 'Lato', sans-serif;
		}
		body {
			margin-left: 15px;
		}
		p {
			font-size: 18px;
		}
	</style>
</head>
<body>
	<h3 style="margin-top: 0; margin-bottom: 10px; font-size: 22px">Terms of Use</h3>
	<!-- <p style="margin-top: 0; margin-bottom: 10px">Last updated: October 07, 2021</p> -->

	<p style="margin-top: 0; margin-bottom: 10px">These Terms of Service govern your use of JobReels, our website located at http://jobreelsapp.com, and any related services provided by JobReels.</p>
    <p style="margin-top: 0; margin-bottom: 10px">When you create an JobReels account or use JobReels, you agree to abide by these Terms of Service and to comply with all applicable laws and regulations. If you do not agree with these Terms of Service, you are prohibited from further using the app, accessing our website, or using any other services provided by JobReels.</p>
    <p style="margin-top: 0; margin-bottom: 10px">If you access or download JobReels from (1) the Apple App Store, you agree to any Usage Rules set forth in the App Store Terms of Service; and/or (2) the Google Play Store, you agree to the Android, Google Inc. Terms and Conditions including the Google Apps Terms of Service.</p>
    <p style="margin-top: 0; margin-bottom: 10px">We, JobReels, reserve the right to review and amend any of these Terms of Service at our sole discretion. Upon doing so, we will update this page and notify you through the app and/or the email address you provided when you created your account. Any changes to these Terms of Service will take effect immediately from the date of publication.</p>
    <p style="margin-top: 0; margin-bottom: 10px">These Terms of Service were last updated on 27 October 2022.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Limitations of Use</h3>
    <p style="margin-top: 0; margin-bottom: 10px">By using JobReels and our website, you warrant on behalf of yourself, any entity who you represent who has entered into these Terms of Service, and your users that you will not:</p>
    <ul style="margin-top: 0; margin-bottom: 10px">
        <li>modify, copy, prepare derivative works of, decompile, or reverse engineer JobReels or any materials and software contained within JobReels or on our website.</li>
        <li>remove any copyright or other proprietary notations from JobReels or any materials and software contained within JobReels or on our website;</li>
        <li>transfer JobReels or any of its associated materials to another person or “mirror” the materials on any other server;</li>
        <li>transfer JobReels or any of its associated materials to another person or “mirror” the materials on any other server;</li>
        <li>use JobReels or its associated services to transmit or publish any harassing, indecent, obscene, fraudulent, or unlawful material;</li>
        <li>use JobReels or its associated services in violation of any applicable laws or regulations;</li>
        <li>use JobReels to send unauthorized advertising or spam;</li>
        <li>use JobReels to send unauthorized advertising or spam;</li>
        <li>use JobReels or its associated services in such a way that may infringe the privacy, intellectual property rights, or other rights of third parties.</li>
    </ul>
    <h3 style="margin-top: 0; margin-bottom: 10px">Intellectual Property</h3>
    <p style="margin-top: 0; margin-bottom: 10px">The intellectual property in the materials in JobReels and on our website are owned by or licensed to JobReels. You may download JobReels, to view, use, and display the application on your mobile device for your personal use only.</p>
    <p style="margin-top: 0; margin-bottom: 10px">This constitutes the grant of a license, not a transfer of title. This license shall automatically terminate if you violate any of these restrictions or these Terms of Service, and may be terminated by JobReels at any time.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">User-Generated Content</h3>
    <p style="margin-top: 0; margin-bottom: 10px">You retain your intellectual property ownership rights over content you submit to us for publication within JobReels and/or on its corresponding website. We will never claim ownership of your content, but we do require a license from you in order to use it.</p>
    <p style="margin-top: 0; margin-bottom: 10px">When you use JobReels or its associated services to post, upload, share, or otherwise transmit content covered by intellectual property rights, you grant to us a non-exclusive, royalty-free, transferable, sub-licensable, worldwide license to use, distribute, modify, run, copy, publicly display, translate, or otherwise create derivative works of your content in a manner that is consistent with your privacy preferences and our Privacy Policy.</p>
    <p style="margin-top: 0; margin-bottom: 10px">The license you grant us can be terminated at any time by deleting your content or account. However, to the extent that we (or our partners) have used your content in connection with commercial or sponsored content, the license will continue until the relevant commercial or post has been discontinued by us.</p>
    <p style="margin-top: 0; margin-bottom: 10px">You give us permission to use your username and other identifying information associated with your account in a manner that is consistent with your privacy preferences, and our Privacy Policy.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Automatic Updates</h3>
    <p style="margin-top: 0; margin-bottom: 10px">You give us permission to download and install updates to JobReels on your device in accordance with your privacy preferences. This permission can be revoked at any time by deleting JobReels from your device.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Liability</h3>
    <p style="margin-top: 0; margin-bottom: 10px">JobReels and the materials in JobReels and on our website are provided on an ‘as is’ basis. To the extent permitted by law, JobReels makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property, or other violation of rights.</p>
    <p style="margin-top: 0; margin-bottom: 10px">In no event shall JobReels or its suppliers be liable for any consequential loss suffered or incurred by you or any third party arising from the use or inability to use JobReels, our website, or any other services provided by JobReels or the materials in JobReels, even if JobReels or an authorized representative has been notified, orally or in writing, of the possibility of such damage.</p>
    <p style="margin-top: 0; margin-bottom: 10px">In the context of this agreement, “consequential loss” includes any consequential loss, indirect loss, real or anticipated loss of profit, loss of benefit, loss of revenue, loss of business, loss of goodwill, loss of opportunity, loss of savings, loss of reputation, loss of use and/or loss or corruption of data, whether under statute, contract, equity, tort (including negligence), indemnity, or otherwise.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Accuracy of Materials</h3>
    <p style="margin-top: 0; margin-bottom: 10px">The materials appearing in JobReels or on our website are not comprehensive and are for general information purposes only. To the extent permitted by law, JobReels does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials in JobReels or on our website, or otherwise relating to such materials or on any resources linked to JobReels and our website.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Links</h3>
    <p style="margin-top: 0; margin-bottom: 10px">JobReels has not reviewed all of the sites linked to JobReels or on its corresponding website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement, approval, or control by JobReels of the site. Use of any such linked website is at your own risk and we strongly advise you make your own investigations with respect to the suitability of those sites.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Licensed Application End User License Agreement (EULA)</h3>
    <p style="margin-top: 0; margin-bottom: 10px">JobReels apps made available through the App Store are licensed, not sold, to you. Your license to each App is subject to your prior acceptance of this Licensed Application End User License Agreement (“Standard EULA”). Your license to any JobReels App under this Standard EULA, and your license to any Third Party App under this Standard EULA is granted by the Application Provider of that Third Party App. Any App that is subject to this Standard EULA is referred to herein as the “Licensed Application.” The Application Provider or JobReels as applicable (“Licensor”) reserves all rights in and to the Licensed Application not expressly granted to you under this Standard EULA.</p>
    <ul style="margin-top: 0; margin-bottom: 10px">
        <li>Scope of License: Licensor grants to you a nontransferable license to use the Licensed Application on any JobReels-branded products that you own or control and as permitted by the Usage Rules. The terms of this Standard EULA will govern any content, materials, or services accessible from or purchased within the Licensed Application as well as upgrades provided by Licensor that replace or supplement the original Licensed Application. Except as provided in the Usage Rules, you may not distribute or make the Licensed Application available over a network where it could be used by multiple devices at the same time. You may not transfer, redistribute or sublicense the Licensed Application and, if you sell your Apple Device to a third party, you must remove the Licensed Application from the Apple Device before doing so. You may not copy (except as permitted by this license and the Usage Rules), reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Licensed Application, any updates, or any part thereof (except as and only to the extent that any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open-sourced components included with the Licensed Application).</li>
        <li>Consent to Use of Data: You agree that Licensor may collect and use technical data and related information—including but not limited to technical information about your device, system and application software, and peripherals—that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Licensed Application. Licensor may use this information, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you.</li>
        <li>Termination. This Standard EULA is effective until terminated by you or Licensor. Your rights under this Standard EULA will terminate automatically if you fail to comply with any of its terms.</li>
        <li>External Services. The Licensed Application may enable access to Licensor’s and/or third-party services and websites (collectively and individually, “External Services”). You agree to use the External Services at your sole risk. Licensor is not responsible for examining or evaluating the content or accuracy of any third-party External Services, and shall not be liable for any such third-party External Services. Data displayed by any Licensed Application or External Service, including but not limited to financial, medical and location information, is for general informational purposes only and is not guaranteed by Licensor or its agents. You will not use the External Services in any manner that is inconsistent with the terms of this Standard EULA or that infringes the intellectual property rights of Licensor or any third party. You agree not to use the External Services to harass, abuse, stalk, threaten or defame any person or entity, and that Licensor is not responsible for any such use. External Services may not be available in all languages or in your Home Country, and may not be appropriate or available for use in any particular location. To the extent you choose to use such External Services, you are solely responsible for compliance with any applicable laws. Licensor reserves the right to change, suspend, remove, disable or impose access restrictions or limits on any External Services at any time without notice or liability to you.</li>
        <li>NO WARRANTY: YOU EXPRESSLY ACKNOWLEDGE AND AGREE THAT USE OF THE LICENSED APPLICATION IS AT YOUR SOLE RISK. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE LICENSED APPLICATION AND ANY SERVICES PERFORMED OR PROVIDED BY THE LICENSED APPLICATION ARE PROVIDED “AS IS” AND “AS AVAILABLE,” WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, AND LICENSOR HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH RESPECT TO THE LICENSED APPLICATION AND ANY SERVICES, EITHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY, OF SATISFACTORY QUALITY, OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY, OF QUIET ENJOYMENT, AND OF NONINFRINGEMENT OF THIRD-PARTY RIGHTS. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY. SHOULD THE LICENSED APPLICATION OR SERVICES PROVE DEFECTIVE, YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR, OR CORRECTION. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</li>
        <li>Limitation of Liability. TO THE EXTENT NOT PROHIBITED BY LAW, IN NO EVENT SHALL LICENSOR BE LIABLE FOR PERSONAL INJURY OR ANY INCIDENTAL, SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR ANY OTHER COMMERCIAL DAMAGES OR LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE LICENSED APPLICATION, HOWEVER CAUSED, REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, OR OTHERWISE) AND EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OF LIABILITY FOR PERSONAL INJURY, OR OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THIS LIMITATION MAY NOT APPLY TO YOU. In no event shall Licensor’s total liability to you for all damages (other than as may be required by applicable law in cases involving personal injury) exceed the amount of fifty dollars ($50.00). The foregoing limitations will apply even if the above stated remedy fails of its essential purpose.</li>
        <li>You may not use or otherwise export or re-export the Licensed Application except as authorized by United States law and the laws of the jurisdiction in which the Licensed Application was obtained. In particular, but without limitation, the Licensed Application may not be exported or re-exported (a) into any U.S.-embargoed countries or (b) to anyone on the U.S. Treasury Department’s Specially Designated Nationals List or the U.S. Department of Commerce Denied Persons List or Entity List. By using the Licensed Application, you represent and warrant that you are not located in any such country or on any such list. You also agree that you will not use these products for any purposes prohibited by United States law, including, without limitation, the development, design, manufacture, or production of nuclear, missile, or chemical or biological weapons.</li>
        <li>The Licensed Application and related documentation are “Commercial Items”, as that term is defined at 48 C.F.R. §2.101, consisting of “Commercial Computer Software” and “Commercial Computer Software Documentation”, as such terms are used in 48 C.F.R. §12.212 or 48 C.F.R. §227.7202, as applicable. Consistent with 48 C.F.R. §12.212 or 48 C.F.R. §227.7202-1 through 227.7202-4, as applicable, the Commercial Computer Software and Commercial Computer Software Documentation are being licensed to U.S. Government end users (a) only as Commercial Items and (b) with only those rights as are granted to all other end users pursuant to the terms and conditions herein. Unpublished-rights reserved under the copyright laws of the United States.</li>
        <li>Except to the extent expressly provided in the following paragraph, this Agreement and the relationship between you and JobReels shall be governed by the laws of the State of California, excluding its conflicts of law provisions. You and JobReels agree to submit to the personal and exclusive jurisdiction of the courts located within the county of Santa Clara, California, to resolve any dispute or claim arising from this Agreement. If (a) you are not a U.S. citizen; (b) you do not reside in the U.S.; (c) you are not accessing the Service from the U.S.; and (d) you are a citizen of one of the countries identified below, you hereby agree that any dispute or claim arising from this Agreement shall be governed by the applicable law set forth below, without regard to any conflict of law provisions, and you hereby irrevocably submit to the non-exclusive jurisdiction of the courts located in the state, province or country identified below whose law governs:</li>
    </ul>
    <p style="margin-top: 0; margin-bottom: 10px">If you are a citizen of any European Union country or Switzerland, Norway or Iceland, the governing law and forum shall be the laws and courts of your usual place of residence.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Specifically excluded from application to this Agreement is that law known as the United Nations Convention on the International Sale of Goods.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Notice regarding Apple</h3>
    <p style="margin-top: 0; margin-bottom: 10px">To the extent that you are using or accessing JobReels on an iOS device, you acknowledge and agree to the terms of this clause. You acknowledge that these Terms of Service are between you and JobReels only, not with Apple Inc. (Apple), and Apple is not responsible for JobReels and any materials available in JobReels.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Apple has no obligation to furnish you with any maintenance and support services with respect to JobReels.</p>
    <p style="margin-top: 0; margin-bottom: 10px">If JobReels fails to conform to any applicable warranty, you may notify Apple and Apple will refund the purchase price of the mobile application to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to JobReels and any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure to conform to any warranty will be our responsibility.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Apple is not responsible for addressing any claims by you or any third party relating to JobReels or your use of JobReels, including but not limited to (1) product liability claims; (2) any claim that our mobile application fails to conform to any applicable legal or regulatory requirement; and (3) claims arising under consumer protection or similar legislation.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Apple is not responsible for the investigation, defence, settlement, and discharge of any third-party claim that our mobile application infringes that third party’s intellectual property rights.</p>
    <p style="margin-top: 0; margin-bottom: 10px">You agree to comply with any applicable third-party terms when using JobReels, including any Usage Rules set forth in the Apple App Store Agreement of Service.</p>
    <p style="margin-top: 0; margin-bottom: 10px">Apple and Apple’s subsidiaries are third-party beneficiaries of these Terms of Service, and upon your acceptance of these Terms of Service, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms of Service against you as a third-party beneficiary of these Terms of Service.</p>
    <p style="margin-top: 0; margin-bottom: 10px">You hereby represent and warrant that (1) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (2) you are not listed on any U.S. Government list of prohibited or restricted parties.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Right to Terminate</h3>
    <p style="margin-top: 0; margin-bottom: 10px">We may suspend or terminate your JobReels account and right to use JobReels and these Terms of Service immediately upon written notice to you for any breach of these Terms of Service.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Severance</h3>
    <p style="margin-top: 0; margin-bottom: 10px">Any term of these Terms of Service which is wholly or partially void or unenforceable is severed to the extent that it is void or unenforceable. The validity of the remainder of these Terms of Service is not affected.</p>
    <h3 style="margin-top: 0; margin-bottom: 10px">Governing Law</h3>
    <p style="margin-top: 0; margin-bottom: 10px">These Terms of Service are governed by and construed in accordance with the laws of Alabama. You irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
    <p style="margin-top: 0; margin-bottom: 10px"></p>
    <p style="margin-top: 0; margin-bottom: 10px"></p>
    <p style="margin-top: 0; margin-bottom: 10px"></p>
    <p style="margin-top: 0; margin-bottom: 10px"></p>

</body>
</html>
